#!/system/bin/sh
#
# All rights reserved by luo2888
#
# Weibo : www.weibo.com/kwangaho
#  QQ   : 625336209
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

GET_BL_VERSION=`getprop ro.bootloader | /sbin/busybox cut -c 1-5`

# For GSM Device

if [ "$GET_BL_VERSION" == "G9006" ] || [ "$GET_BL_VERSION" == "G9008" ]; then

	/sbin/busybox dd if=/tmp/kltechn.img of=/dev/block/platform/msm_sdcc.1/by-name/boot

elif [ "$GET_BL_VERSION" == "G900F" ]; then

	/sbin/busybox dd if=/tmp/kltexx.img of=/dev/block/platform/msm_sdcc.1/by-name/boot

#For CDMA Device

elif [ "$GET_BL_VERSION" == "SCL23" ] || [ "$GET_BL_VERSION" == "SC04F" ]; then

	/sbin/busybox dd if=/tmp/kltekdi.img of=/dev/block/platform/msm_sdcc.1/by-name/boot

elif [ "$GET_BL_VERSION" == "G900P" ]; then

	/sbin/busybox dd if=/tmp/kltespr.img of=/dev/block/platform/msm_sdcc.1/by-name/boot

#For Other Device

else

	/sbin/busybox dd if=/tmp/klte.img of=/dev/block/platform/msm_sdcc.1/by-name/boot

fi
