#!/system/bin/sh
#
# All rights reserved by luo2888
#
# Weibo : www.weibo.com/kwangaho
#  QQ   : 625336209
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

cat /system/etc/boeffla-config-v2 > /data/app/boeffla-config-v2.apk

setprop ro.telephony.default_network 10

GET_BL_VERSION=`getprop ro.bootloader|cut -c 1-5`

mount -o remount,rw /system

# For GSM Device

if [ "$GET_BL_VERSION" == "G900F" ]; then

  setprop ro.product.model "SM-G900F"
  setprop ro.product.device "kltexx"
  setprop ro.build.description "kltexx-user 4.4.2 KOT49H G900FXXU1ANG2 release-keys"
  setprop ro.build.fingerprint "samsung/kltexx/klte:4.4.2/KOT49H/G900FXXU1ANG2:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900A" ]; then

  setprop ro.product.model "SM-G900A"
  setprop ro.product.device "klteatt"
  setprop ro.build.description "klteatt-user 4.4.2 KOT49H G900AUCU2AND3 release-keys"
  setprop ro.build.fingerprint "samsung/klteatt/klte:4.4.2/KOT49H/G900AUCU2AND3:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900M" ]; then

  setprop ro.product.model "SM-G900M"
  setprop ro.product.device "klteeub"
  setprop ro.build.description "klteub-user 4.4.2 KOT49H G900MUBU1ANCE release-keys"
  setprop ro.build.fingerprint "samsung/klteub/klte:4.4.2/KOT49H/G900MUBU1ANCE:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900T" ]; then

  setprop ro.product.model "SM-G900T"
  setprop ro.product.device "kltetmo"
  setprop ro.build.description "kltetmo-user 4.4.2 KOT49H G900TUVU1BNH5 release-keys"
  setprop ro.build.fingerprint "samsung/kltetmo/kltetmo:4.4.2/KOT49H/G900TUVU1BNH5:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900S" ]; then

  setprop ro.product.model "SM-G900S"
  setprop ro.product.device "klteskt"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900I" ]; then

  setprop ro.product.model "SM-G900I"
  setprop ro.product.device "kltedv"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"
  mv /system/app/com.android.nfc-1.apk /system/app/com.android.nfc-1.apk.bak

elif [ "$GET_BL_VERSION" == "G900L" ]; then

  setprop ro.product.model "SM-G900L"
  setprop ro.product.device "kltelgt"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900K" ]; then

  setprop ro.product.model "SM-G900K"
  setprop ro.product.device "kltektt"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900W8" ]; then

  setprop ro.product.model "SM-G900W8"
  setprop ro.product.device "kltecan"
  setprop ro.build.description "kltevl-user 4.3 JSS15J N900W8VLUBMJ4 release-keys"
  setprop ro.build.fingerprint "samsung/kltevl/kltecan:4.3/JSS15J/N900W8VLUBMJ4:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G9006" ]; then

  setprop ro.product.model "SM-G9006V"
  setprop ro.product.device "kltezn"
  setprop ro.build.description "kltezn-user 4.4.2 KOT49H G9006VZNU1ANCH release-keys"
  setprop ro.build.fingerprint "samsung/kltezn/klte:4.4.2/KOT49H/G9006VZNU1ANCH:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G9008" ]; then

  setprop ro.product.model "SM-G9008V"
  setprop ro.product.device "kltezm"
  setprop ro.build.description "kltezm-user 4.4.2 KOT49H G9008VZNU1ANCH release-keys"
  setprop ro.build.fingerprint "samsung/kltezm/klte:4.4.2/KOT49H/G9008VZNU1ANCH:user/release-keys"
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

#For CDMA Device

elif [ "$GET_BL_VERSION" == "SCL23" ]; then

  setprop ro.product.model "SM-G900J"
  setprop ro.product.device "kltekdi"
  setprop ro.build.description "kltekdi-user 4.4.2 KOT49H SCL23KDU1AND1 release-keys"
  setprop ro.build.fingerprint "samsung/SCL23/SCL23:4.4.2/KOT49H/SCL23KDU1AND1:user/release-keys"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV,RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop telephony.lteOnCdmaDevice 1cc
  mv /system/app/com.android.nfc-1.apk /system/app/com.android.nfc-1.apk.bak

elif [ "$GET_BL_VERSION" == "SC04F" ]; then

  setprop ro.product.model "SM-G900J"
  setprop ro.product.device "kltedcm"
  setprop ro.build.description "kltedcm-user 4.4.2 KOT49H SC04FOMU1VOD2 release-keys"
  setprop ro.build.fingerprint "samsung/SC04F/SC04F:4.4.2/KOT49H/SC04FOMU1VOD2:user/release-keys"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV,RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop telephony.lteOnCdmaDevice 1
  mv /system/app/com.android.nfc-1.apk /system/app/com.android.nfc-1.apk.bak

elif [ "$GET_BL_VERSION" == "G900P" ]; then

  setprop ro.product.model "SM-G900P"
  setprop ro.product.device "kltespr"
  setprop ro.build.description "kltespr-user 4.4.2 KOT49H G900PVPU1ANCB release-keys"
  setprop ro.build.fingerprint "samsung/kltespr/kltespr:4.4.2/KOT49H/G900PVPU1ANCB:user/release-keys"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV,RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop telephony.lteOnCdmaDevice 1
  mv /system/app/com.android.nfc-1.apk /system/app/com.android.nfc-1.apk.bak

elif [ "$GET_BL_VERSION" == "G900V" ]; then

  setprop ro.product.model "SM-G900V"
  setprop ro.product.device "kltevzw"
  setprop ro.build.description "kltevzw-user 4.4.2 KOT49H G900VVRU1ANE9 release-keys"
  setprop ro.build.fingerprint "Verizon/kltevzw/kltevzw:4.4.2/KOT49H/G900VVRU1ANE9:user/release-keys"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV,RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop telephony.lteOnCdmaDevice 1

elif [ "$GET_BL_VERSION" == "G900R" ]; then

  setprop ro.product.model "SM-G900R"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop telephony.lteOnCdmaDevice 1

else

  setprop ro.product.model $GET_BL_VERSION

fi
