#!/system/bin/sh
#
# All rights reserved by luo2888
#
# Weibo : www.weibo.com/kwangaho
#  QQ   : 625336209
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
setprop ro.telephony.default_network 9

GET_BL_VERSION=`getprop ro.bootloader|cut -c 1-5`

mount -o remount,rw /system

if [ "$GET_BL_VERSION" != "I9508" ]; then

  cat /system/etc/boeffla_config-v2 > /data/app/boeffla_config-v2.apk

fi

# For GSM Device

if [ "$GET_BL_VERSION" == "G900F" ]; then

  setprop ro.product.model "SM-G900F"
  setprop ro.product.device "kltexx"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900M" ]; then

  setprop ro.product.model "SM-G900M"
  setprop ro.product.device "klteeub"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900T" ]; then

  setprop ro.product.model "SM-G900T"
  setprop ro.product.device "kltetmo"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900S" ]; then

  setprop ro.product.model "SM-G900S"
  setprop ro.product.device "klteskt"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900I" ]; then

  setprop ro.product.model "SM-G900I"
  setprop ro.product.device "kltedv"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900L" ]; then

  setprop ro.product.model "SM-G900L"
  setprop ro.product.device "kltelgt"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900K" ]; then

  setprop ro.product.model "SM-G900K"
  setprop ro.product.device "kltektt"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G900W" ]; then

  setprop ro.product.model "SM-G900W8"
  setprop ro.product.device "kltecan"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G9006" ]; then

  setprop ro.product.model "SM-G9006V"
  setprop ro.product.device "kltezn"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "G9008" ]; then

  setprop ro.product.model "SM-G9008V"
  setprop ro.product.device "kltezm"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "SC04F" ]; then

  setprop ro.product.model "SM-G900D"
  setprop ro.product.device "kltedcm"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

elif [ "$GET_BL_VERSION" == "I9508" ]; then

  setprop ro.product.model "GT-I9508V"
  setprop ro.product.device "jsglte"
  setprop ro.telephony.ril_class JsglteRIL
  setprop telephony.lteOnGsmDevice 1
  setprop ro.telephony.ril.v3 "newDialCode"

#For CDMA Device

elif [ "$GET_BL_VERSION" == "SCL23" ]; then

  setprop ro.product.model "SM-G900J"
  setprop ro.product.device "kltekdi"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnCdmaDevice 1

elif [ "$GET_BL_VERSION" == "G900P" ]; then

  setprop ro.product.model "SM-G900P"
  setprop ro.product.device "kltespr"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnCdmaDevice 1

elif [ "$GET_BL_VERSION" == "G900V" ]; then

  setprop ro.product.model "SM-G900V"
  setprop ro.product.device "kltevzw"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnCdmaDevice 1

elif [ "$GET_BL_VERSION" == "G900R" ]; then

  setprop ro.product.model "SM-G900R"
  setprop ro.product.device "klteusc"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "NV"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnCdmaDevice 1

elif [ "$GET_BL_VERSION" == "G9009" ]; then

  setprop ro.product.model "SM-G9009D"
  setprop ro.product.device "k3gduos"
  setprop telephony.sms.pseudo_multipart 1
  setprop ril.subscription.types "RUIM"
  setprop ro.cdma.home.operator.numeric "operator_numeric"
  setprop ro.cdma.home.operator.alpha "operator_alpha"
  setprop ro.telephony.default_cdma_sub "default_cdma_sub"
  setprop ro.telephony.ril.v3 "newDriverCallU,newDialCode"
  setprop ro.telephony.ril_class KlteRIL
  setprop telephony.lteOnCdmaDevice 1

else

  setprop ro.product.model $GET_BL_VERSION

fi
