#!/system/bin/sh

echo 185 >/proc/sys/vm/swappiness

if [ -e /dev/block/vnswap0 ];then
  cat /proc/swaps | grep -i vnswap
  if [ "$?" == "1" ];then
    exho "Opening VnSwap..."
    log -t VNSWAP "Opening VnSwap!"
    echo 1572864000 >/sys/block/vnswap0/disksize
    mkswap /dev/block/vnswap0
    swapon -p 2 /dev/block/vnswap0
  else
    echo "SWAP has been opened!"
    log -t VNSWAP "SWAP has been opened!"
  fi
fi