#!/system/bin/sh

count=`cat /data/system/count`
COUNTFILE=/data/system/count
PRELOAD_APP_DIR=/system/third-app

if [ "$count" == "" ]; then
	touch /data/system/count
	echo "0" > /data/system/count
fi

let "count+=1" 
echo $count > $COUNTFILE

APP=/system/etc/iFlyIME
APPDIR=/system/app

mount -o remount,rw /system

if [ "$count" == "1" ]; then
	cat $APP > $APPDIR/iFlyIME.apk
fi

for file in `ls $PRELOAD_APP_DIR`; do
	if [ "$count" == "1" ]; then
		sleep 15
		pm install -r $PRELOAD_APP_DIR/$file	
	elif [ "$count" == "5" ]; then
		sleep 15
		pm install -r $PRELOAD_APP_DIR/$file
	fi
done
